# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bms_voltage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bms_voltage.proto',
  package='bms_voltage',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x62ms_voltage.proto\x12\x0b\x62ms_voltage\"\xfa\x02\n\nBmsVoltage\x12\x11\n\treal_time\x18\x02 \x02(\x03\x12\x11\n\tdevice_id\x18\x01 \x02(\x05\x12\x10\n\x08\x63pu_time\x18\x13 \x02(\x03\x12\x11\n\tvoltage_0\x18\x03 \x02(\x05\x12\x11\n\tvoltage_1\x18\x04 \x02(\x05\x12\x11\n\tvoltage_2\x18\x05 \x02(\x05\x12\x11\n\tvoltage_3\x18\x06 \x02(\x05\x12\x11\n\tvoltage_4\x18\x07 \x02(\x05\x12\x11\n\tvoltage_5\x18\x08 \x02(\x05\x12\x11\n\tvoltage_6\x18\t \x02(\x05\x12\x11\n\tvoltage_7\x18\n \x02(\x05\x12\x11\n\tvoltage_8\x18\x0b \x02(\x05\x12\x11\n\tvoltage_9\x18\x0c \x02(\x05\x12\x12\n\nvoltage_10\x18\r \x02(\x05\x12\x12\n\nvoltage_11\x18\x0e \x02(\x05\x12\x12\n\nvoltage_12\x18\x0f \x02(\x05\x12\x12\n\nvoltage_13\x18\x10 \x02(\x05\x12\x12\n\nvoltage_14\x18\x11 \x02(\x05\x12\x12\n\nvoltage_15\x18\x12 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BMSVOLTAGE = _descriptor.Descriptor(
  name='BmsVoltage',
  full_name='bms_voltage.BmsVoltage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='real_time', full_name='bms_voltage.BmsVoltage.real_time', index=0,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='bms_voltage.BmsVoltage.device_id', index=1,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cpu_time', full_name='bms_voltage.BmsVoltage.cpu_time', index=2,
      number=19, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_0', full_name='bms_voltage.BmsVoltage.voltage_0', index=3,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_1', full_name='bms_voltage.BmsVoltage.voltage_1', index=4,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_2', full_name='bms_voltage.BmsVoltage.voltage_2', index=5,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_3', full_name='bms_voltage.BmsVoltage.voltage_3', index=6,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_4', full_name='bms_voltage.BmsVoltage.voltage_4', index=7,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_5', full_name='bms_voltage.BmsVoltage.voltage_5', index=8,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_6', full_name='bms_voltage.BmsVoltage.voltage_6', index=9,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_7', full_name='bms_voltage.BmsVoltage.voltage_7', index=10,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_8', full_name='bms_voltage.BmsVoltage.voltage_8', index=11,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_9', full_name='bms_voltage.BmsVoltage.voltage_9', index=12,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_10', full_name='bms_voltage.BmsVoltage.voltage_10', index=13,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_11', full_name='bms_voltage.BmsVoltage.voltage_11', index=14,
      number=14, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_12', full_name='bms_voltage.BmsVoltage.voltage_12', index=15,
      number=15, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_13', full_name='bms_voltage.BmsVoltage.voltage_13', index=16,
      number=16, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_14', full_name='bms_voltage.BmsVoltage.voltage_14', index=17,
      number=17, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_15', full_name='bms_voltage.BmsVoltage.voltage_15', index=18,
      number=18, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=413,
)

DESCRIPTOR.message_types_by_name['BmsVoltage'] = _BMSVOLTAGE

BmsVoltage = _reflection.GeneratedProtocolMessageType('BmsVoltage', (_message.Message,), dict(
  DESCRIPTOR = _BMSVOLTAGE,
  __module__ = 'bms_voltage_pb2'
  # @@protoc_insertion_point(class_scope:bms_voltage.BmsVoltage)
  ))
_sym_db.RegisterMessage(BmsVoltage)


# @@protoc_insertion_point(module_scope)
