# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timing_packets.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='timing_packets.proto',
  package='timing_packets',
  syntax='proto2',
  serialized_pb=_b('\n\x14timing_packets.proto\x12\x0etiming_packets\"s\n\x0cTimingPacket\x12\x13\n\x0btime_bucket\x18\x05 \x01(\x03\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x11\n\tpacket_id\x18\x02 \x01(\x03\x12\x11\n\ttime_sent\x18\x03 \x01(\x03\x12\x15\n\rresponse_time\x18\x04 \x01(\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TIMINGPACKET = _descriptor.Descriptor(
  name='TimingPacket',
  full_name='timing_packets.TimingPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_bucket', full_name='timing_packets.TimingPacket.time_bucket', index=0,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='timing_packets.TimingPacket.client_id', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='packet_id', full_name='timing_packets.TimingPacket.packet_id', index=2,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_sent', full_name='timing_packets.TimingPacket.time_sent', index=3,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response_time', full_name='timing_packets.TimingPacket.response_time', index=4,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['TimingPacket'] = _TIMINGPACKET

TimingPacket = _reflection.GeneratedProtocolMessageType('TimingPacket', (_message.Message,), dict(
  DESCRIPTOR = _TIMINGPACKET,
  __module__ = 'timing_packets_pb2'
  # @@protoc_insertion_point(class_scope:timing_packets.TimingPacket)
  ))
_sym_db.RegisterMessage(TimingPacket)


# @@protoc_insertion_point(module_scope)
