// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package bms_voltage.bms_voltage



object BmsVoltageProto {
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChFibXNfdm9sdGFnZS5wcm90bxILYm1zX3ZvbHRhZ2UivQQKCkJtc1ZvbHRhZ2USGwoJcmVhbF90aW1lGAIgAigDUghyZWFsV
  GltZRIbCglkZXZpY2VfaWQYASACKAVSCGRldmljZUlkEhkKCGNwdV90aW1lGBMgAigDUgdjcHVUaW1lEhsKCXZvbHRhZ2VfMBgDI
  AIoBVIIdm9sdGFnZTASGwoJdm9sdGFnZV8xGAQgAigFUgh2b2x0YWdlMRIbCgl2b2x0YWdlXzIYBSACKAVSCHZvbHRhZ2UyEhsKC
  XZvbHRhZ2VfMxgGIAIoBVIIdm9sdGFnZTMSGwoJdm9sdGFnZV80GAcgAigFUgh2b2x0YWdlNBIbCgl2b2x0YWdlXzUYCCACKAVSC
  HZvbHRhZ2U1EhsKCXZvbHRhZ2VfNhgJIAIoBVIIdm9sdGFnZTYSGwoJdm9sdGFnZV83GAogAigFUgh2b2x0YWdlNxIbCgl2b2x0Y
  WdlXzgYCyACKAVSCHZvbHRhZ2U4EhsKCXZvbHRhZ2VfORgMIAIoBVIIdm9sdGFnZTkSHQoKdm9sdGFnZV8xMBgNIAIoBVIJdm9sd
  GFnZTEwEh0KCnZvbHRhZ2VfMTEYDiACKAVSCXZvbHRhZ2UxMRIdCgp2b2x0YWdlXzEyGA8gAigFUgl2b2x0YWdlMTISHQoKdm9sd
  GFnZV8xMxgQIAIoBVIJdm9sdGFnZTEzEh0KCnZvbHRhZ2VfMTQYESACKAVSCXZvbHRhZ2UxNBIdCgp2b2x0YWdlXzE1GBIgAigFU
  gl2b2x0YWdlMTU="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}