// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package timing_packets.timing_packets



object TimingPacketsProto {
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChR0aW1pbmdfcGFja2V0cy5wcm90bxIOdGltaW5nX3BhY2tldHMiqwEKDFRpbWluZ1BhY2tldBIfCgt0aW1lX2J1Y2tldBgFI
  AEoA1IKdGltZUJ1Y2tldBIbCgljbGllbnRfaWQYASABKAlSCGNsaWVudElkEhsKCXBhY2tldF9pZBgCIAEoA1IIcGFja2V0SWQSG
  woJdGltZV9zZW50GAMgASgDUgh0aW1lU2VudBIjCg1yZXNwb25zZV90aW1lGAQgASgDUgxyZXNwb25zZVRpbWU="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}