// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package timing_packets.timing_packets



object TimingPacketsProto {
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChR0aW1pbmdfcGFja2V0cy5wcm90bxIOdGltaW5nX3BhY2tldHMi0AEKDFRpbWluZ1BhY2tldBIfCgt0aW1lX2J1Y2tldBgBI
  AEoA1IKdGltZUJ1Y2tldBIjCg1leHBlcmltZW50X2lkGAIgASgJUgxleHBlcmltZW50SWQSGwoJY2xpZW50X2lkGAMgASgJUghjb
  GllbnRJZBIbCglwYWNrZXRfaWQYBCABKANSCHBhY2tldElkEhsKCXRpbWVfc2VudBgFIAEoA1IIdGltZVNlbnQSIwoNcmVzcG9uc
  2VfdGltZRgGIAEoA1IMcmVzcG9uc2VUaW1l"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}